Repository developers-against-repressions/case-212, pull requests merged in 2019-09, with the labels that each got.

#806 За вашу и нашу свободу!
  signed/2b13095c65c9f2fde93a973c92a3e04b
Labels: ok

#834 added sign
  signed/adghdfrshfgshjgj
Labels: ok

#833 Create Gdej8439-JDbfdi7483_vvjfYdfn35
  signed/Gdej8439-JDbfdi7483_vvjfYdfn35
Labels: ok

#830 aa1bba6b6729bcf93c791d26
  signed/0x8b5a1a44e492dc4daa1bba6b6729bcf93c791d26
Labels: ok

#814 Create fiou8jfu934YY*&^&TR%^$GGYU
  signed/fiou8jfu934YY*&^&TR%^$GGYU
Labels: ok

#813 Вместе мы сила!
  signed/637d5421-2e47-4288-a6d7-6b84a97c19a1
Labels: ok

#812 kotenko signature
  signed/0Y8g0YLQsNC6INC70Y7QsdC70Y4g0YHQstC+0Y4g0YHRgtGA0LDQvdGDINC4INC90LXQvdCw0LLQuNC20YMg0LPQvtGB0YPQtNCw0YDRgdGC0LLQvg==
Labels: ok

#807 create ycukengnirt.txt
  signed/ycukengnirt.txt
Labels: ok

#815 add signature
  signed/3959c321-ae2e-440d-b3be-f285ba4a6d93.txt
Labels: ok

#816 За себя и за Пашку Устинова! (и остальных конечно же)
  signed/a5ec18c2-a7c6-4868-bed8-40ad5a813941.txt
Labels: ok

#817 add myself
  signed/B10897D6-074E-4825-A653-4C96D5F3A2A5
Labels: ok

#820 Create sign-9363738-Maxim-Kosterin
  signed/sign-9363738-Maxim-Kosterin
Labels: ok

#819 Signed
  signed/c4057b4b35a44ed585ec91eff41c60de
Labels: ok

#821 Подписался
  signed/3cc2ef79963d6dcfd0c1cb2ca22f8505
Labels: ok

#822 Create znxFTQtWqbQUOisv1FKT-rEEP3qzkOBgJJjUtk85B
  signed/znxFTQtWqbQUOisv1FKT-rEEP3qzkOBgJJjUtk85B
Labels: ok

#825 signed
  signed/e81d2879002dc17dfb3770355e15142a616c0a2a51dbd1250ffffcbcbc981479c06346776f0527752095c2a7a173af6052f0bda4ff48eebc32e7c1b4bab4c57a
Labels: ok

#827 Create rudnevskiy-mindbox-somerandomdigitslol
  signed/rudnevskiy-mindbox-somerandomdigitslol
Labels: ok

#828 Sign
  signed/qazwsxedcrfvtgbyhnujmikolp.txt
Labels: ok

#829 Signed
  signed/1e0aee6ae6868462b39b89feb0525c0c
Labels: ok

#848 Create fire-alkazar.txt
  signed/fire-alkazar.txt
Labels: ok

#836 Alexey Moskalev
  signed/5978ad22b9383b12b34f6830168e7dad
Labels: ok

#837 add budylnikov
  signed/d10742bf4d8bc12b059eb2470caf64927d9900792cf45c3205cf9acae156e5d9
Labels: ok

#838 signature
  signed/31b2eb33-184e-4dd5-99aa-26ecffe32c11
Labels: ok

#839 Create bc0a2793-8f26-4875-a349-4e49c2522728
  signed/bc0a2793-8f26-4875-a349-4e49c2522728
Labels: ok

#840 Added signature
  signed/237fdbf5-e2d8-4f89-80ba-bbce033e283c.txt
Labels: ok

#854 Aidarbek signed
  signed/aidarbek
Labels: ok

#841 свободу
  signed/+AVcWQmDEJbPzB0utFhsuzEjruBgePJ8rC1GC7RTNhY=<3
Labels: ok

#842 add signaure
  signed/faSOI3ap9sQUbbnOoZDqESG
Labels: ok

#843 signed
  signed/f3e02340-a15c-4742-8e7f-cbac13fa2057
Labels: ok

#844 Added signature
  signed/ec83c92514064cbcd1d6878e7bc2471a
Labels: ok

#845 Create sign_406eb252bfd54e1dbd3b43b766cf313f
  signed/sign_406eb252bfd54e1dbd3b43b766cf313f
Labels: ok

#846 add sign
  signed/43e69a8b-2f97-4be5-53e4-efe687294f93
Labels: ok

#851 Create 510E3794364B79033D18CEB3D145A4B8
  signed/510E3794364B79033D18CEB3D145A4B8
Labels: ok

#852 Create ;jgfiybr14
  signed/;jgfiybr14
Labels: ok

#853 Create pavel-tomsk
  signed/pavel-tomsk
Labels: ok

#832 Create putin_huilo_201909191122
  signed/putin_huilo_201909191122
Labels: ok

#818 Create a1e1b35400d74a138d0dd4767845b4df
  signed/a1e1b35400d74a138d0dd4767845b4df
Labels: ok

#826 Create d0cdb6fb84794b176778fa1c6a247c6e
  signed/d0cdb6fb84794b176778fa1c6a247c6e
Labels: ok

#913 Create 4du4as323
  signed/4du4as323
Labels: incorrect

#1087 Create B6mDLdcdNk7VsNO
  signed/B6mDLdcdNk7VsNO
Labels: incorrect

#1125 Add english version from #429 as a separate file
  README.en.md
  README.md
  pre-readme.md
Labels: enhancement

#1311 Create Signing212achlexboy
  Signing212achlexboy
Labels: incorrect

#1176 Добавлены подписи из закрытых PRов в старом стиле (когда добавляли строчки в README)
  signed/UTYKgIUYg978oIUKB
Labels: attention

#1352 Signed
  signed/4e8b70b9-4f81-4d0d-bfb3-950a01768046.txt
Labels: incorrect

#1619 Свободу политзаключенным!
  signed/14CE83DE-A67E-4582-A408-DBE937A8659A.txt
Labels: ok

#1593 Signed by Ilya Venner
  signed/5148797b-1f43-4ebe-85b6-5bf00dd21b09-ilyavenner.signed
Labels: ok

#1630 Create VoVaVc_signin_21:40
  signed/VoVaVc_signin_21:40
Labels: ok

#1628 Create 878778lkju8787h345kk
  signed/878778lkju8787h345kk
Labels: ok

#1629 Rename 10cb684f-8ef6-4b5e-91b2-5fc81f6b0c7e to signed/10cb684f-8ef6-4…
  signed/10cb684f-8ef6-4b5e-91b2-5fc81f6b0c7e
Labels: ok

#1625 signature dtsvetkov
  f5d0e38e-a51b-4fa5-a40a-2716bc1223a1
Labels: incorrect

#1671 Create 6700f464-3b59-46ba-98af-ce71beb3aae2
  6700f464-3b59-46ba-98af-ce71beb3aae2
Labels: root

#1634 Create JSQT8WyG94yFb!
  JSQT8WyG94yFb!
Labels: root

#869 Добавление ссылки на GUID generator
  README.md
Labels: enhancement

#784 Исправление порядка имени и фамилии
  README.md
Labels: attention

#1693 Create 2a8ce706-65ae-4dd5-8a2b-c85b47f34d40
  2a8ce706-65ae-4dd5-8a2b-c85b47f34d40
Labels: root

#1720 Create .knlbkjvgcjkhxjkvb;khbvljkvfcj
  .knlbkjvgcjkhxjkvb;khbvljkvfcj
Labels: root

#1712 910e0ea993d25dce078b063302e050c7
  910e0ea993d25dce078b063302e050c7
Labels: root

#1701 +1
  q8g2arggkjcq8vepkedm
Labels: root

#1215 Old signature: Add job
  signed/old_list.txt
Labels: enhancement

#1763 +++
  signed/f5c00ddf-2b2f-4384-ab76-d073142e8ba1
Labels: ok

#1366 Update README.en.md
  README.en.md
Labels: enhancement

#1807 signed
  signed/e03ac7bc-aeba-4c09-911b-7beb4563ad13
Labels: ok

#1242 typos fixed
  README.en.md
Labels: enhancement

#1809 add signs 496aa4f9-5948-4226-becc-9aee9706f6e0
  signed/496aa4f9-5948-4226-becc-9aee9706f6e0
Labels: ok

#1810 Create 10cda9b3-01c8-44ee-b07a-af9aaec91d1d
  signed/10cda9b3-01c8-44ee-b07a-af9aaec91d1d
Labels: ok

#1664 Added 615b
  signed/6a5b573f7ff987027602c7edf14538c78a1d627b.txt
Labels: ok

#1811 Create 36cb04ba-145c-494e-b1d2-7d316ea1acef
  signed/36cb04ba-145c-494e-b1d2-7d316ea1acef
Labels: ok

#1846 Signed Up
  singed_up
Labels: root

#1876 Create c33a6df3-1d8d-48bc-91be-fc6aede38714
  signed/c33a6df3-1d8d-48bc-91be-fc6aede38714
Labels: ok

#1909 Add files via upload
  signed/2019091913051212121212.txt
Labels: incorrect

#1947 sign petition indukaev
  galhsdfljshdfasdflkhj
Labels: root

#1936 create d91bc64f-a6e6-4d30-8059-b5354a871f7e
  d91bc64f-a6e6-4d30-8059-b5354a871f7e
Labels: root

#1881 Create 4666da0e-5b41-44c9-9147-c00d10d4a92a
  4666da0e-5b41-44c9-9147-c00d10d4a92a
Labels: root

#1879 Create a101dff0-a0ad-4747-b694-ea271836c59b
  signed/a101dff0-a0ad-4747-b694-ea271836c59b
Labels: incorrect

#1887 Create victorych_add_to_list
  sign/victorych_add_to_list
Labels: incorrect

#1696 signed
  signed/f608a9a23a176e9a374daa863fa88313
Labels: incorrect

#1905 Add me please
  4cc32505-1c75-48bd-ae94-a7dee8d125a1
  signed/4cc32505-1c75-48bd-ae94-a7dee8d125a1
Labels: incorrect

#2037 1628
  signed/a392b4d6-db9f-11e9-8a34-2a2ae2dbcce4
Labels: incorrect

#2058 подпись 1628
  signed/c5e9ab1d-d153-48e3-b437-37b1ee21abb7
Labels: incorrect

#1873 подпись
  signed/a219c1f9-f7a6-44c3-b1f5-56b29e7014f5
  update_readme.py
Labels: enhancement

#1537 Commit and push signature
  .travis.yml
  push.sh
Labels: enhancement

#2090 Create NoFutureIsNotOurIdea
  signed/NoFutureIsNotOurIdea
Labels: ok

#2091 Create 73980112-1698-443b-b02a-1c386aca45d8---212
  signed/73980112-1698-443b-b02a-1c386aca45d8---212
Labels: ok

#1667 fix translation
  README.en.md
Labels: enhancement

#2097 Create dc9ef745-4e20-47a7-adcf-014aa972ad47
  signed/dc9ef745-4e20-47a7-adcf-014aa972ad47
Labels: ok

#2098 add people
  signed/0A69DE7C-1F03-4804-BD52-23E282834010
  signed/0A69DE7C-1F03-4804-BD52-23E28283408E
Labels: ok

#2120 added 052a3677-f22a-4186-ad57-aa91e237ec77
  signed/052a3677-f22a-4186-ad57-aa91e237ec77
Labels: ok

#2121 Create alexander_gornik
  signed/alexander_gornik
Labels: ok

#2123 Signing
  signed/6a9f6a7c-f6ba-48b2-b8bb-108d206f3aac
Labels: ok

#2127 Create 87c3ca72-af7f-4516-9aed-0098e7b203df
  signed/87c3ca72-af7f-4516-9aed-0098e7b203df
Labels: ok

#2128 Add Aleksandr Petukhov sign
  signed/9c026e24-3123-4496-bf4a-4065c8add2d0
Labels: ok

#2130 Create 44674567hdhtyu4uhery6dfghth
  signed/44674567hdhtyu4uhery6dfghth
Labels: ok

#2132 add one
  signed/b1a020c7-5c86-4201-90d8-bd5c8d75d187
Labels: ok

#2135 Create fe3f2031-078d-414e-83d7-3f51eb19e6e5
  signed/fe3f2031-078d-414e-83d7-3f51eb19e6e5
Labels: ok

#2134 freedom
  signed/de59c90c-12cd-4f1a-8cc1-11d58e5dccc4
Labels: ok

#2247 sign added
  signed/e3ddd2bd-1f88-4817-ab0a-af4fdd05222f
Labels: incorrect

#2215 add some automation
  .github/workflows/sign_check.yml
  .github/workflows/update_readme.yml
  .travis.yml
  push.sh
Labels: enhancement

#2260 sign
  signed/ef6dd10e-5d07-482f-931c-373a01ebb887
Labels: ok

#2261 Create pv2309urd
  signed/pv2309urd
Labels: ok

#2262 sign: repression system is a disaster
  signed/5eb63bbbe01eeed093cb22bb8f5acdc3.txt
Labels: ok

#2263 Create 22327c90-3c1e-4e6d-ae5e-e1e8cc14cdeb
  signed/22327c90-3c1e-4e6d-ae5e-e1e8cc14cdeb
Labels: ok
